#!/bin/bash
# Create all directories
dirs=(
  "app/(auth)/login"
  "app/(dashboard)/dashboard"
  "app/(dashboard)/orders/create"
  "app/(dashboard)/orders/[id]/edit"
  "app/(dashboard)/orders/bulk-upload"
  "app/(dashboard)/users"
  "app/(dashboard)/dealers"
  "app/(dashboard)/invoices"
  "app/(dashboard)/reports"
  "app/(dashboard)/settings"
  "app/api/auth/signout"
  "app/api/dashboard/stats"
  "app/api/orders/[id]"
  "app/api/orders/bulk-upload"
  "app/api/orders/bulk-actions"
  "app/api/orders/export"
  "app/api/orders/upload-template"
  "app/api/users/[id]"
  "app/api/dealers/[id]"
  "app/api/invoices/[id]"
  "app/api/locations"
  "app/api/sources"
  "app/api/reports/dealer"
  "app/api/reports/agent"
  "components/layout"
  "components/orders"
  "components/dashboard"
  "components/dealers"
  "components/users"
  "components/invoices"
  "components/reports"
  "components/ui"
  "lib/auth"
  "lib/db"
  "lib/validations"
  "drizzle/migrations"
  ".github/workflows"
  "public"
)
for d in "${dirs[@]}"; do
  mkdir -p "$d"
done
echo "All directories created"
